## Don't print a new line at the start of the prompt
## add_newline = false
## Disables the line_break module, making the prompt a single line.
## [line_break]
## disabled = true

## Replace the "â¯" symbol in the prompt
## [character]
## symbol = "$"

## Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

#[aws]
#format = '[$symbol($profile )(\($region\) )]($style)'
## style = "bold blue"
## symbol = "ğŸ…° "
#[aws.region_aliases]
#eu-west-1 = "eu"
## [aws.profile_aliases]
## picture-admin=picture

## I'd like to be able to get rid of the "on" prefix in a future version
#[git_branch]
#symbol = "î‚ "

## How to make this do something?
##[git_commit]

##commit_hash_length = 4
## [directory]
## style = "bold cyan"
## truncate_to_repo = false
## truncation_length = 5

## Language configs might be useful when they're less wordy someday.

#[ruby]
#disabled = true
##symbol = "ï» "


#[python]
#disabled = true
##symbol = "îœ¼"
##style = "bold green"

#[golang]
#disabled = true
##symbol = "ï³‘"

#[nodejs]
#disabled = true
##symbol = "îœ˜"
##style = "bold yellow"jh
#
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "â€‹"
untracked = "â€‹"
modified = "â€‹"
staged = "â€‹"
renamed = "â€‹"
deleted = "â€‹"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
